# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: discover-workshops-registration
      PGDATA: /var/lib/postgresql/data/apertis-qa-report

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
